version: '3.8'

services:
  client-service:
    build: ./jaeger-client
    container_name: client-service
    ports:
      - "8081:8081"
    environment:
      - SERVICE_HOST=server-service
      - SERVICE_PORT=8082
      - JAEGER_HOST=jaeger
      - JAEGER_LOG_SPAN_ENABLED=true
    depends_on:
      - jaeger
    networks:
      - microservices-network

  server-service:
    build: ./jaeger-server
    container_name: server-service
    ports:
      - "8082:8082"
    depends_on:
      - jaeger
    environment:
      - JAEGER_HOST=jaeger
      - JAEGER_LOG_SPAN_ENABLED=true
    networks:
      - microservices-network

  jaeger:
    image: jaegertracing/all-in-one:1.6.0
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "9411:9411"
      - "14268:14268"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge